import React, {Component} from "react";
import {Container, List} from "semantic-ui-react";
import './font.css';
import './articleList.css';


class ArticleList extends Component {

    render () {
        return (
            <Container>
                <List celled relaxed className="article-list">
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Content>
                            Java原生数据类型的拆装箱                        
                        </List.Content>
                    </List.Item>
                </List>
            </Container>
        );
    }
}

export default ArticleList